name: idf
channels:
  - conda-forge
  - defaults
dependencies:
  - antlr-python-runtime=4.7.2=py36_1000
  - asciitree=0.3.3=py_2
  - asn1crypto=0.24.0=py36_1003
  - atk=2.25.90=hb9dd440_1002
  - attrs=19.1.0=py_0
  - blas=1.1=openblas
  - bokeh=1.0.4=py36_1000
  - boost-cpp=1.68.0=h11c811c_1000
  - bottleneck=1.2.1=py36h3010b51_1001
  - bzip2=1.0.6=h14c3975_1002
  - ca-certificates=2019.3.9=hecc5488_0
  - cairo=1.16.0=ha4e643d_1000
  - cartopy=0.17.0=py36h0aa2c8f_1004
  - cdsapi=0.1.3=py_0
  - certifi=2019.3.9=py36_0
  - cf_units=2.0.1=py36h3010b51_1002
  - cffi=1.12.2=py36hf0e25f4_1
  - cftime=1.0.3.4=py36h3010b51_1000
  - chardet=3.0.4=py36_1003
  - click=7.0=py_0
  - click-plugins=1.0.4=py_0
  - cligj=0.5.0=py_0
  - cloudpickle=0.8.0=py_0
  - cryptography=2.5=py36hb7f436b_1
  - curl=7.64.0=h646f8bb_0
  - cycler=0.10.0=py_1
  - cytoolz=0.9.0.1=py36h14c3975_1001
  - dask=1.1.4=py_0
  - dask-core=1.1.4=py_0
  - dbus=1.13.0=h4e0c4b3_1000
  - descartes=1.1.0=py_2
  - distributed=1.26.0=py36_1
  - expat=2.2.5=hf484d3e_1002
  - fasteners=0.14.1=py_3
  - fiona=1.8.4=py36h1c6dbfb_1002
  - fontconfig=2.13.1=h2176d3f_1000
  - freetype=2.9.1=h94bbf69_1005
  - freexl=1.0.5=h14c3975_1002
  - gdal=2.4.0=py36h1c6dbfb_1002
  - gdk-pixbuf=2.36.12=h49783d7_1002
  - geopandas=0.4.1=py_0
  - geos=3.7.1=hf484d3e_1000
  - geotiff=1.4.3=h1105359_1000
  - gettext=0.19.8.1=h9745a5d_1001
  - giflib=5.1.4=h14c3975_1001
  - glib=2.58.3=hf63aee3_1001
  - gobject-introspection=1.58.2=py36h2da5eee_1000
  - graphite2=1.3.13=hf484d3e_1000
  - gst-plugins-base=1.14.4=hdf3bae2_1001
  - gstreamer=1.14.4=h66beb1c_1001
  - gtk2=2.24.31=hb68c50a_1001
  - harfbuzz=2.3.1=h6824563_0
  - hdf4=4.2.13=h9a582f1_1002
  - hdf5=1.10.4=nompi_h11e915b_1105
  - heapdict=1.0.0=py36_1000
  - humanize=0.5.1=py_1
  - icu=58.2=hf484d3e_1000
  - idna=2.8=py36_1000
  - intel-openmp=2019.1=144
  - jinja2=2.10=py_1
  - jpeg=9c=h14c3975_1001
  - json-c=0.13.1=h14c3975_1001
  - kealib=1.4.10=he7154bc_1002
  - kiwisolver=1.0.1=py36h6bb024c_1002
  - krb5=1.16.3=hc83ff2d_1000
  - libblas=3.8.0=2_h9ac9557_netlib
  - libcblas=3.8.0=2_h9ac9557_netlib
  - libcurl=7.64.0=h01ee5af_0
  - libdap4=3.19.1=hd48c02d_1000
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=hf484d3e_1005
  - libgcc-ng=7.3.0=hdf63c60_0
  - libgdal=2.4.0=h982c1cc_1002
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libiconv=1.15=h14c3975_1004
  - libkml=1.3.0=h328b03d_1009
  - liblapack=3.8.0=2_h9ac9557_netlib
  - liblapacke=3.8.0=2_h9ac9557_netlib
  - libnetcdf=4.6.2=hbdf4f91_1001
  - libopenblas=0.3.3=h5a2b251_3
  - libpng=1.6.36=h84994c4_1000
  - libpq=10.6=h13b8bad_1000
  - libspatialindex=1.8.5=hf484d3e_1003
  - libspatialite=4.3.0a=hb5ec416_1026
  - libssh2=1.8.0=h1ad7b7a_1003
  - libstdcxx-ng=7.3.0=hdf63c60_0
  - libtiff=4.0.10=h648cc4a_1001
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.8=h143f9aa_1005
  - libxslt=1.1.32=h4785a14_1002
  - llvmlite=0.28.0=py36hdbcaa40_0
  - locket=0.2.0=py_2
  - lxml=4.3.2=py36h23eabaa_0
  - lz4=2.1.6=py36ha8eefa0_1000
  - lz4-c=1.8.1.2=0
  - mapclassify=2.0.1=py_0
  - markupsafe=1.1.1=py36h14c3975_0
  - matplotlib=3.0.3=py36_0
  - matplotlib-base=3.0.3=py36h167e16e_0
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py36_0
  - mkl_random=1.0.2=py36_0
  - monotonic=1.5=py_0
  - msgpack-python=0.6.1=py36h6bb024c_0
  - munch=2.3.2=py_0
  - ncurses=6.1=hf484d3e_1002
  - numba=0.41.0=py36h637b7d7_1000
  - numcodecs=0.6.3=py36hf484d3e_0
  - numpy=1.16.2=py36_blas_openblash1522bff_0
  - numpy-base=1.16.2=py36hde5b4d6_0
  - olefile=0.46=py_0
  - openblas=0.3.3=h9ac9557_1001
  - openjpeg=2.3.0=hf38bd82_1003
  - openssl=1.0.2r=h14c3975_0
  - owslib=0.17.1=py_0
  - packaging=19.0=py_0
  - palettable=3.1.1=py_0
  - pandas=0.24.2=py36hf484d3e_0
  - pango=1.40.14=h4ea9474_1004
  - partd=0.3.9=py_0
  - patsy=0.5.1=py_0
  - pcre=8.41=hf484d3e_1003
  - pillow=5.4.1=py36h00a061d_1000
  - pip=19.0.3=py36_0
  - pixman=0.34.0=h14c3975_1003
  - poppler=0.67.0=h2ad7f00_6
  - poppler-data=0.4.9=1
  - postgresql=10.6=h66cca7a_1000
  - proj4=5.2.0=h14c3975_1001
  - psutil=5.6.1=py36h14c3975_0
  - psycopg2=2.7.7=py36hb7f436b_0
  - pthread-stubs=0.4=h14c3975_1001
  - pycparser=2.19=py36_1
  - pyepsg=0.4.0=py_0
  - pykdtree=1.3.1=py36h3010b51_1002
  - pyke=1.1.1=py36_1000
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.3.1=py_0
  - pyproj=1.9.6=py36hc0953d3_1000
  - pyqt=5.6.0=py36h13b7fb3_1008
  - pysal=2.0.0=py_0
  - pyshp=2.1.0=py_0
  - pysocks=1.6.8=py36_1002
  - python=3.6.7=hd21baee_1002
  - python-dateutil=2.8.0=py_0
  - pytz=2018.9=py_0
  - pyyaml=5.1=py36h14c3975_0
  - qt=5.6.2=hce4f676_1013
  - readline=7.0=hf8c457e_1001
  - requests=2.21.0=py36_1000
  - rtree=0.8.3=py36_1000
  - scipy=1.2.1=py36_blas_openblash1522bff_0
  - seaborn=0.9.0=py_0
  - setuptools=40.8.0=py36_0
  - shapely=1.6.4=py36h092830f_1002
  - sip=4.18.1=py36hf484d3e_1000
  - six=1.12.0=py36_1000
  - sortedcontainers=2.1.0=py_0
  - sqlalchemy=1.3.1=py36h14c3975_0
  - sqlite=3.26.0=h67949de_1001
  - statsmodels=0.9.0=py36h3010b51_1000
  - tblib=1.3.2=py_1
  - tk=8.6.9=h84994c4_1000
  - toolz=0.9.0=py_1
  - tornado=6.0.1=py36h14c3975_0
  - tzcode=2018g=h14c3975_1001
  - udunits2=2.2.27.6=h4e0c4b3_1001
  - urllib3=1.24.1=py36_1000
  - util-linux=2.21=0
  - wheel=0.33.1=py36_0
  - xarray=0.11.3=py36_0
  - xerces-c=3.2.2=hac72e42_1001
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.9=h14c3975_1004
  - xorg-libsm=1.2.3=h4937e3b_1000
  - xorg-libx11=1.6.7=h14c3975_1000
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.2=h14c3975_1007
  - xorg-libxext=1.3.3=h14c3975_1004
  - xorg-libxrender=0.9.10=h14c3975_1002
  - xorg-libxt=1.1.5=h14c3975_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - zarr=2.2.0=py_1
  - zict=0.1.4=py_0
  - zlib=1.2.11=h14c3975_1004
  - zstd=1.3.8=h7510944_1002
prefix: /home/lunet/gylc4/miniconda2/envs/idf

